#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

rm ./server/src/schema/*.*

../esphome/script/build_jsonschema.py $@ --output-path "./server/src/schema"

cd ../esphome-docs

sphinx-build . _build -E

cd -

cp -r ../esphome-docs/schema.json ./server/src/schema.json

rm ../esphome-docs/schema.json